### ISSUE TITLE
About the test-version registration

### ISSUE THREAD

**Issue by MimaoQiuQiu** [Cubeseed/Frontend#21]
I made a non-UI test version of the registration function. It now can fetch the user group data (farmers, marketplace, etc.) from the back end. Allow a user to register with their information. 

This is my flow: get the group data -> users select their group using group names and connected with the group url -> users input their info -> submit the form to the backend -> display the user info on the page

I want to list some problems that I met.

1. there is an is_active property, which I think is to indicate if the user is available or not. However, I don't know how to set it to true. Every time I try to create a new user, the is_active property is always false.

2. I'm not able to view the user I created. I try to use API: /userauth/users/{id}/ to fetch the user's information. It gives me "Authentication credentials were not provided." in the response body. I don't know if I was using this in the wrong way.

3. When I try to move to implement the login function. I was using API: /auth/token/ to get a JSON web token to prove the authentication. However, it gives me "No active account found with the given credentials". I believe it's related to question 1. The is_active property needs to be true if I want to get authenticated.

4. When I try to edit the user's information (I thought I could change the is_active to true) using API: /userauth/user/{id}/, method is PUT, it gives me "Authentication credentials were not provided". I probably use it wrong. Need some help on that as well.

I appreciate whoever has some ideas on the problem I met. We can discuss them. Thank you very much. I may probably update more problems under this issue, this is just for now.

**Comment by sgarciahelguera** [comment]
I think this was prior to our meeting, but just so that it is visible for everybody:
That is the expected behavior.
The user registers with username, email and password, and is created as inactive. 
A user with the moderator group has to approve the user, which sets the mentioned flag to true. 
You need to login as a moderator (the default user has all groups, so moderator too), and update is_active on the user.
After that the user can login and go on (e.g. create a profile).
